version: '3.8'

services:
  umusanzu_fn:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      ENVIRONMENT: development
    ports:
      - "80:80"
    networks:
      - app-network
    mem_limit: 2g  # Limit Next.js container to 2g of RAM

networks:
  app-network: