name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - staging
permissions:
  checks: write
env:
  API_URL: ${{ secrets.API_URL }}
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci && npm run build
      - name: Deploy to Firebase Hosting
        env:
          API_URL: ${{ secrets.API_URL }}
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_UMUSANZU_DIGITAL_UD }}
          channelId: live
          projectId: umusanzu-digital-ud
