name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - staging
permissions:
  checks: write
env:
  API_URL: ${{ secrets.API_URL }}
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_UMUSANZU_DIGITAL_UD }}
          channelId: live
          projectId: umusanzu-digital-ud
